baseURL = "https://code-and-lego.bintz.io/"
languageCode = "en-us"
title = "Code and LEGO"
# theme = "m10c"
theme = "hello-friend-ng"
[Author]
name = "Alexandre Bintz"
[params]
author = "Alexandre Bintz"
description = "Hello Internet! I'm Alex, I'm a big fan of LEGO and occasional iOS programmer. I write about what I learn and what I do. Follow me on GitHub for my programming projects and on Flickr for my LEGO projects."
homeSubtitle = "A blog about programming and LEGO"
[[params.social]]
name = "github"
url = "https://github.com/alexbinary"
[[params.social]]
name = "flickr"
url = "https://www.flickr.com/photos/163799831@N07/"
[[params.social]]
name = "twitter"
url = "https://twitter.com/alex_loves_lego"
[[params.social]]
name = "email"
url = "mailto:alexandre@bintz.io"
[menu]
[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"
