baseURL = "https://code-and-lego.bintz.io/"
languageCode = "en-us"
title = "Code and LEGO"
# theme = "m10c"
theme = "hugo-nuo"
[params]
  author = "Alexandre Bintz"
  description = "Hello Internet! I'm Alex, I'm a big fan of LEGO and occasional iOS programmer. I write about what I learn and what I do. Follow me on GitHub for my programming projects and on Flickr for my LEGO projects."
[[params.social]]
  name = "github"
  url = "https://github.com/alexbinary"
[[params.social]]
  name = "flickr"
  url = "https://www.flickr.com/photos/163799831@N07/"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/alex_loves_lego"
[[params.social]]
  name = "email"
  url = "mailto:alexandre@bintz.io"

[[menu.main]]
  name = "Blog"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Projects"
  weight = 20
  identifier = "works"
  url = "/posts"

[[menu.main]]
  name = "How-tos"
  weight = 30
  identifier = "tags"
  url = "/tags/"