baseURL = "https://code-and-lego.bintz.io/"
languageCode = "en-us"
title = "Code and LEGO"
# theme = "m10c"
theme = "hello-friend"
[params]
  author = "Alexandre Bintz"
  description = "Hello Internet! I'm Alex, I'm a big fan of LEGO and occasional iOS programmer. I write about what I learn and what I do. Follow me on GitHub for my programming projects and on Flickr for my LEGO projects."
[[params.social]]
  name = "github"
  url = "https://github.com/alexbinary"
[[params.social]]
  name = "flickr"
  url = "https://www.flickr.com/photos/163799831@N07/"
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/alex_loves_lego"
[[params.social]]
  name = "email"
  url = "mailto:alexandre@bintz.io"
[languages]
  [languages.en]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "code and LEGO"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Blog"
        url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "howtos"
        name = "How-tos"
        url = "/showcase"